# Generated by Django 5.0.6 on 2024-05-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', verbose_name='Аватар пользователя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='vk_id',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
