# Generated by Django 5.0.6 on 2024-05-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_vk_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, upload_to='avatars/', verbose_name='Аватар пользователя'),
        ),
    ]
